name: CI

permissions:
  contents: read
  actions: read

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 21]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Configure npm registry
        run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        
      - name: Validate package.json
        run: |
          # Check for circular dependencies
          if grep -q '"@sbeeredd04/auto-git"' package.json; then
            echo "Error: Circular dependency detected in package.json"
            exit 1
          fi
          echo "package.json validation passed"
        
      - name: Clean install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        
      - name: Run lint (if available)
        run: npm run lint
        continue-on-error: true
        
      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Test CLI installation
        run: |
          # Try npm link, but continue if it fails due to permissions
          npm link || echo "npm link failed (expected in CI), continuing..."
          # Test the CLI directly from node_modules if link failed
          if command -v auto-git >/dev/null 2>&1; then
            auto-git --help
          else
            echo "Testing CLI directly from bin directory"
            node bin/auto-git.js --help
          fi
        
      - name: Test configuration
        run: auto-git config
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Configure npm registry
        run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        
      - name: Validate package.json
        run: |
          # Check for circular dependencies
          if grep -q '"@sbeeredd04/auto-git"' package.json; then
            echo "Error: Circular dependency detected in package.json"
            exit 1
          fi
          echo "package.json validation passed"
        
      - name: Clean install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        
      - name: Test package creation
        run: |
          npm pack
          # Verify the package was created
          ls -la *.tgz
          # Test package installation
          npm install -g ./sbeeredd04-auto-git-*.tgz || echo "Global install failed (expected in CI)"
        
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: '*.tgz' 