name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests (if any)
        run: npm test
        continue-on-error: true
        
      - name: Update package version from tag
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "Setting version to $VERSION"
          npm version $VERSION --no-git-tag-version
        
      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create Success Comment
        if: success()
        run: |
          echo "✅ Successfully published @sbeeredd04/auto-git@$VERSION to NPM!"
          echo "📦 Install with: npm install -g @sbeeredd04/auto-git" 